const menuButton=document.querySelector('.menu-toggle'),navigation=document.querySelector('#navigation');
function closeMenu(){menuButton?.setAttribute('aria-expanded','false');navigation?.classList.remove('open')}
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));navigation.classList.toggle('open',open)});
navigation?.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&navigation?.classList.contains('open')){closeMenu();menuButton.focus()}});
matchMedia('(min-width:761px)').addEventListener('change',closeMenu);
navigation?.querySelectorAll('a').forEach(a=>{if(a.pathname===location.pathname)a.setAttribute('aria-current','page')});
const names={'tracy':'Tracy','mountain-house':'Mountain House','lathrop':'Lathrop','manteca':'Manteca','dublin':'Dublin','livermore':'Livermore'};
document.querySelectorAll('[data-city]').forEach(button=>{if(button.tagName!=='BUTTON')return;button.addEventListener('click',()=>{document.querySelectorAll('button[data-city]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});const name=names[button.dataset.city];const image=document.querySelector('#city-image');image.src='/assets/img/city-'+button.dataset.city+'.jpg';image.alt='A view of '+name+', California';document.querySelector('#city-caption').textContent=name+', California';document.querySelector('#city-status').textContent='Showing '+name+', California'})});
const filterForm=document.querySelector('#listing-filters');
if(filterForm){
 const cards=[...document.querySelectorAll('.listing-card')],catalog=document.querySelector('.catalog');
 function restore(){const query=new URLSearchParams(location.search);for(const el of filterForm.elements){if(el.name)el.value=query.get(el.name)??({status:'all',beds:'0',sort:'high'}[el.name]||'')}}
 function apply(write=true){const values=Object.fromEntries(new FormData(filterForm));let count=0;cards.forEach(card=>{const d=card.dataset;const show=(values.status==='all'||d.status===values.status)&&(!values.city||d.city===values.city)&&(!values.max||Number(d.price)<=Number(values.max))&&Number(d.beds)>=Number(values.beds)&&(!values.q||d.address.includes(values.q.trim().toLowerCase()));card.hidden=!show;if(show)count++});cards.sort((a,b)=>values.sort==='address'?a.dataset.address.localeCompare(b.dataset.address):values.sort==='low'?Number(a.dataset.price)-Number(b.dataset.price):Number(b.dataset.price)-Number(a.dataset.price)).forEach(card=>catalog.append(card));document.querySelector('#result-count').textContent=count+' '+(count===1?'property':'properties');document.querySelector('.empty-results').hidden=count!==0;if(write){const query=new URLSearchParams();Object.entries(values).forEach(([k,v])=>{if(v&&v!==({status:'all',beds:'0',sort:'high'}[k]))query.set(k,v)});history.pushState(null,'',location.pathname+(query.size?'?'+query:''))}}
 restore();apply(false);filterForm.addEventListener('submit',e=>{e.preventDefault();apply()});filterForm.addEventListener('reset',()=>{setTimeout(()=>apply(),0)});window.addEventListener('popstate',()=>{restore();apply(false)});
}
for(const form of document.querySelectorAll('.request-form')){
 const params=new URLSearchParams(location.search);const intent=form.querySelector('[name=intent]');if(intent?.tagName==='SELECT'&&[...intent.options].some(o=>o.value===params.get('intent')))intent.value=params.get('intent');
 const city=form.querySelector('[name=city]');if(city&&params.has('city'))city.value=params.get('city');
 if(params.has('property'))form.querySelector('[name=message]').value='I would like to know more about '+params.get('property')+'.';
 const review=form.querySelector('.request-review');let message='';
 form.addEventListener('input',()=>{review.hidden=true});
 form.addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form));const labels={intent:'I’m looking to',name:'Name',email:'Email',phone:'Phone',address:'Property address',city:'City / area',zip:'ZIP',timing:'Timing',message:'Message'};message=Object.entries(values).filter(([,v])=>v.trim()).map(([key,v])=>(labels[key]||key)+': '+v.trim()).join('\n\n');review.querySelector('pre').textContent=message;const subject=values.intent==='Home valuation'?'Home valuation: '+values.address:'Website inquiry: '+values.intent;review.querySelector('.email-request').href='mailto:superiorservicerealtor@gmail.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(message);review.hidden=false;review.focus();});
 form.querySelector('.copy-request').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(message);form.querySelector('.request-status').textContent='Copied. Paste this into an email to superiorservicerealtor@gmail.com. Nothing has been sent.'}catch{form.querySelector('.request-status').textContent='Copy is unavailable in this browser. Select the message above or use Save request.'}});
 form.querySelector('.download-request').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([message],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='agent4life-request.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);form.querySelector('.request-status').textContent='Saved to your device. Nothing has been sent.'});
}
