from pathlib import Path
import json,re,html,shutil
from urllib.parse import quote,urlsplit
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'implementation';E=lambda v:html.escape(str(v),quote=True)
data=json.loads((OUT/'data/listings.json').read_text(encoding='utf-8'));listings=data['listings']
nav=[('listings','Properties'),('sellers','Sellers'),('buyers','Buyers'),('communities','Communities'),('about','Emad'),('team','Team'),('contact','Contact')]
header='<header class="header"><a class="brand" href="/" aria-label="Agent4Life Realty home"><img src="/assets/img/agent4life-logo.png" width="636" height="112" alt="Agent4Life Realty"></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">+</span></button><nav id="navigation" aria-label="Main navigation">'+''.join(f'<a href="/{p}/">{label}</a>' for p,label in nav)+'<a class="nav-contact" href="/home-value/">Home value ↗</a></nav></header>'
footer='''<footer><div class="wrap footer-links"><a href="/testimonials/">Client stories</a><a href="/home-value/">Home valuation</a><a href="/contact/?intent=Relocating">Relocation</a><a href="/listings/?status=sold">Sold properties</a><a href="https://www.instagram.com/realtoremadbasma/">Instagram</a><a href="https://www.facebook.com/Tracyrealestateandhomes">Facebook</a><a href="https://www.youtube.com/channel/UCcWFGqt9LnLadEw60vt4-yw">YouTube</a><a href="/privacy/">Privacy</a></div><div class="wrap"><p>© 2026 Agent4Life Realty. Emad A. Basma · DRE #01441193.</p><p>Equal Housing Opportunity</p><a href="#">Back to top ↑</a></div></footer>'''
def link(path,label,kind='primary'):return f'<a class="button {kind}" href="{E(path)}">{label} <span aria-hidden="true">↗</span></a>'
def picture(src,alt,cls=''):return f'<img class="{cls}" src="/{E(src)}" alt="{E(alt)}" width="1280" height="850" loading="lazy">'
def cta(title='Let’s put a plan behind it.',text='Talk directly with Emad about your next move.',path='/contact/',label='Talk with Emad'):return f'<section class="closing"><div class="wrap"><div><h2>{title}</h2><p>{text}</p></div>{link(path,label,"white")}</div></section>'
def hero(kicker,title,text,img=None):return f'<section class="inner-hero {"with-image" if img else ""}"><div class="wrap"><p class="kicker">{kicker}</p><h1>{title}</h1><p>{text}</p></div>{picture(img,title.replace("<br>"," ")) if img else ""}</section>'
def page(route,title,body,description=None):
 path=OUT/route/'index.html';path.parent.mkdir(parents=True,exist_ok=True)
 path.write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#080808"><title>{E(title)} | Agent4Life Realty</title><meta name="description" content="{E(description or title+' with Emad Basma and Agent4Life Realty in Tracy, California.')}"><link rel="canonical" href="https://agent4liferealty.com/{route}/"><link rel="icon" href="/assets/img/favicon.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="/site.css"><script src="/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a>{header}<main id="main">{body}</main>{footer}</body></html>''',encoding='utf-8')
def steps(items):return '<ol class="steps">'+''.join(f'<li><h3>{title}</h3><p>{text}</p></li>' for title,text in items)+'</ol>'
def faq(items):return '<div class="faq">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)+'</div>'
def split(title,text):return f'<section class="section wrap editorial"><h2>{title}</h2><div>{text}</div></section>'
# Validate public listing data before creating any listing pages.
ids=set();slugs=set()
for p in listings:
 assert re.fullmatch(r'[a-z0-9-]+',p['slug']) and p['slug'] not in slugs,'Invalid or duplicate slug'
 assert p['id'] not in ids,'Duplicate listing id'
 ids.add(p['id']);slugs.add(p['slug'])
 assert p['status'] in ['active','pending','sold','showcase'],'Invalid status'
 assert all(isinstance(p[n],(int,float)) and p[n]>=0 for n in ['price','beds','sqft']),'Invalid number'
 for img in p['images']:assert (OUT/img).resolve().is_relative_to(OUT.resolve()) and (OUT/img).is_file(),f'Missing local image {img}'
 assert not p.get('tourUrl') or urlsplit(p['tourUrl']).scheme=='https','Tour URL must be HTTPS'

def card(p,featured=False):
 label={'active':'For sale','pending':'Pending','sold':'Sold','showcase':'Showcase'}[p['status']]
 media=picture(p['images'][0],p['address']) if p['images'] else '<div class="no-photo">Property photos coming soon</div>'
 return f'<a class="listing-card" href="/listings/{E(p["slug"])}/" data-status="{p["status"]}" data-city="{E(p["city"])}" data-price="{p["price"]}" data-beds="{p["beds"]}" data-address="{E(p["address"].lower())}"><div class="listing-image">{media}<span class="status">{label}</span></div><div class="listing-copy"><p class="listing-price">${p["price"]:,}</p><h2>{E(p["address"])}</h2><p>{E(p["city"])}, CA {E(p["zip"])}</p><p class="listing-facts">{p["beds"]} beds &nbsp; / &nbsp; {E(p["baths"])} baths &nbsp; / &nbsp; {p["sqft"]:,} sq. ft.</p><small>Listing office: {E(p["listingOffice"])}</small></div></a>'

page('sellers','Sell with Emad',hero('Sell with Emad','Your home deserves<br>a bigger introduction.','Personal preparation. Visible marketing. Direct guidance from the first conversation to the handoff.','assets/img/truck-pacheco.jpg')+split('Put a plan<br>before the sign.','<p class="lead">The right starting point is your situation—not a generic checklist.</p><p>Talk with Emad about your timeline, your home, and what comes next. Together, you can decide which preparations matter, how to present the property, and how to approach the market.</p>'+link('/home-value/','Request a home valuation'))+'<section class="soft section"><div class="wrap"><p class="kicker">From preparation to closing</p><h2>A clear path to market.</h2>'+steps([('Start with the home and your goals.','Walk through the property, discuss timing, and identify the information needed to shape a selling plan.'),('Prepare what matters.','Prioritize presentation and practical improvements. Emad can coordinate with trusted vendors as part of the plan you agree on.'),('Price with context.','Review comparable homes, property condition, and competing listings together. Pricing is a conversation grounded in the property and the market.'),('Give it a proper introduction.','Build a marketing plan around the home: property photography and video, open houses, and Agent4Life’s distinctive mobile billboard.'),('Understand the whole offer.','Review price alongside timing, contingencies, and the buyer’s terms. Emad helps you compare the details before deciding.'),('Stay informed through the finish.','Keep track of inspections, agreed repairs, deadlines, and the closing steps with clear communication along the way.')])+'</div></section>'+split('Before you list.',faq([('Do I need to renovate first?','Start with a walkthrough. Some homes benefit from focused preparation; others are better positioned with a different plan. Discuss the work and budget before spending.'),('Can I sell while planning my next purchase?','Yes—bring both timelines to the first conversation so Emad can help you consider how the two moves fit together.'),('How do I find out what my home could sell for?','Request a personal valuation. Share the address, condition, recent improvements, and timing so the discussion is specific to your home.')]))+cta('Let’s talk about your home.','Start with your address. Build the plan together.','/home-value/','Get a personal valuation'))
page('buyers','Buy with a plan',hero('Buying with Agent4Life','Find the home.<br>Know your next step.','A first purchase, more space, a different neighborhood—start with what your next home needs to do for you.','assets/img/city-mountain-house.jpg')+split('Start with<br>your priorities.','<p class="lead">A good search starts before the first showing.</p><p>Share your preferred areas, budget, timeline, and must-haves. Emad and the team help you focus your search, compare homes, and understand the decisions along the way.</p>'+link('/listings/','Explore properties'))+'<section class="soft section"><div class="wrap"><h2>From the first look<br>to the keys.</h2>'+steps([('Set the brief.','Separate essentials from nice-to-haves. Consider location, space, daily routines, and your timing.'),('Talk with a lender early.','If you plan to finance, discuss your budget and loan options with a lender. Ask Emad for an introduction if you need a starting point.'),('Visit and compare.','Look beyond photos. Take time to consider condition, layout, and how each property matches your priorities.'),('Prepare an offer.','Work through price, proposed timing, and terms with your agent before making a decision.'),('Follow through carefully.','Stay engaged with inspections, lender requests, and the agreed deadlines. Ask questions whenever something is unclear.'),('Plan the move.','Coordinate the final walkthrough, closing, and practical details of your move with the people involved.')])+'</div></section>'+split('Coming from<br>somewhere else?','<p class="lead">Let’s narrow down where to start.</p><p>Tell the team about your move, the areas you are considering, and when you can visit. They can help you organize a more focused search across Tracy, the Central Valley, and the Tri-Valley.</p>'+link('/contact/?intent=Relocating','Plan a relocation'))+cta())

cities=[('tracy','Tracy','Historic downtown. Room for a new chapter.','Agent4Life’s home base, with an office on East 10th Street. Start a conversation about the parts of Tracy that fit your search.'),('mountain-house','Mountain House','A different pace, close to Tracy.','Explore Mountain House with your space, timing, and daily routines in mind. The team can help you compare the available homes.'),('lathrop','Lathrop','Explore what’s taking shape.','Consider Lathrop alongside neighboring Central Valley communities. Talk through home styles, location, and your priorities with the team.'),('manteca','Manteca','A Central Valley possibility.','Make Manteca part of a focused local search. Bring your must-haves and the team can help you decide where to look next.'),('dublin','Dublin','Make the Tri-Valley part of the plan.','Compare Dublin with your other preferred areas. Emad and the team can help you connect your budget and goals to a practical search.'),('livermore','Livermore','A place to explore, a move to plan.','Consider Livermore as part of your Tri-Valley search. Discuss the homes, timing, and priorities that matter to your next chapter.')]
page('communities','Our communities',hero('Tracy roots. A wider reach.','Find your place.','Six communities. One team to help you explore what fits.')+'<div class="wrap community-jump">'+''.join(f'<a href="#{slug}">{name}</a>' for slug,name,_,_ in cities)+'</div>'+''.join(f'<section id="{slug}" class="city-section wrap">{picture("assets/img/city-"+slug+".jpg",name+", California")}<div><p class="kicker">{name}</p><h2>{title}</h2><p>{text}</p>{link("/listings/?city="+quote(name),"View "+name+" properties","dark")}<a class="inline-link" href="/contact/?intent=Buying&city={quote(name)}">Ask about {name}</a></div></section>' for slug,name,title,text in cities)+cta())

page('about','Meet Emad Basma',hero('Emad A. Basma','A name behind<br>every promise.','Founder of Agent4Life Realty. Real estate since 2004. A career built around service.','assets/img/emad-portrait.jpg')+split('Service is<br>the foundation.','<p class="lead">Before real estate, Emad served for 22 years as a Santa Clara County deputy sheriff.</p><p>That experience shaped his approach to representing clients: honest communication, careful attention, and responsibility for the work. His own homebuying experiences inspired him to enter real estate in 2004.</p><p>He works primarily with sellers and also represents buyers with a range of goals. His experience includes equity sales, foreclosures, and short sales. He is a Certified Distressed Property Expert and a graduate of California State University, Chico.</p><p>As the founder of Agent4Life, he leads a team that includes his son, Nizar, and daughter, Sonya. Together, they help clients navigate their next move with a personal approach.</p><p>DRE #01441193</p>')+'<section class="testimonial"><div class="wrap"><p class="kicker">The Agent4Life promise</p><h2>Superior service is not an option.<br>It’s a promise.</h2></div></section>'+split('See the promise<br>in practice.','<p>The billboard truck, property videos, and hands-on open houses make the marketing visible. Clear communication keeps the client at the center of the process.</p><div class="action-row">'+link('/sellers/','See the selling approach')+link('/testimonials/','Read client stories','dark')+'</div>')+cta())
team=[('emad','Emad Basma','Founder','Emad brings a 22-year law enforcement background and real estate experience dating to 2004. He leads Agent4Life with direct communication and a personal commitment to clients.','2099144751','superiorservicerealtor@gmail.com'),('nizar','Nizar Basma','Real estate agent','Raised in Tracy, Nizar combines his connection to the area with a background in technology. His work emphasizes attention to detail, strategy, and guidance through important decisions.','2099144751','basmarealty@gmail.com'),('sonya','Sonya Jones','Real estate agent','Sonya brings a background in healthcare and a personal understanding of how much a home can mean. She focuses on care, communication, and helping clients find a place for their next chapter.','2098793344','sellwithsonya@yahoo.com'),('rosendo','Rosendo Serna','Real estate agent','Born and raised in Stockton and a Manteca resident since 1995, Rosendo brings local knowledge and 26 years of correctional and deputy service to his work with clients.','2094790358','serna2239@comcast.net'),('jamese','Jamese Johnson','Real estate agent','Jamese serves the San Joaquin and Tri-Valley areas. Her background in nonprofit projects and clinical research informs her organized, people-focused approach to real estate.','2096400423','jamesejohnsonrealty@gmail.com')]
page('team','Meet Team Basma',hero('The Agent4Life team','Personal attention.<br>A shared standard.','Meet the people behind the name, and connect directly with the agent you want to work with.')+'<section class="wrap people">'+''.join(f'<article id="{slug}">{picture("assets/img/team-"+slug+".jpg",name)}<div><p class="kicker">{role}</p><h2>{name}</h2><p>{bio}</p><div class="person-contact"><a href="tel:+1{phone}">{phone[:3]}.{phone[3:6]}.{phone[6:]}</a><a href="mailto:{email}">{email}</a></div></div></article>' for slug,name,role,bio,phone,email in team)+'</section>'+cta())
quotes=[('Sume Aktar','Great team , great agent for buy and sell houses. Really worked hard for us even though it was a national holiday’s. Appreciated everything specially Emad.'),('Angelina Lopez Luviano','Emad is great! You can trust him! Helped us with selling a property. He is available for you at all times, quick to answer. He communicates every step of the process. I 100% recommend him.'),('Karen','Agent4Life Realty does amazing work!! I have both purchased and sold with them. They are extremely knowledgeable, trustworthy and committed. They made the process seamless and updated you every step of the way.'),('Danielle Faasisila','Emad made the house buying process so easy! He has excellent communication and helped us get a great deal! We highly recommend using him as your realtor!!'),('Mai Lam','Emad and his team have really taken care of us throughout the years. He has helped us sell our home and just got us into our forever home. Such an honest and professional team and I recommend to all my family, friends and neighbors.'),('Fam Del Carpio','Great Realtor, amazing team!')]
page('testimonials','Client stories',hero('In their own words','The work is personal.<br>So is the feedback.','Client comments shared on the previous Agent4Life website. Longer reviews are excerpted.')+'<section class="wrap reviews">'+''.join(f'<figure><blockquote>“{E(text)}”</blockquote><figcaption>{name}</figcaption></figure>' for name,text in quotes)+'</section>'+cta())

def form(valuation=False):
 purpose='<input type="hidden" name="intent" value="Home valuation">' if valuation else '<label>I’m looking to<select name="intent" id="intent"><option>Selling</option><option>Buying</option><option>Relocating</option><option>General question</option></select></label>'
 address='<label class="full">Property address<input name="address" autocomplete="street-address" required></label><label>City<input name="city" autocomplete="address-level2" required></label><label>ZIP code<input name="zip" autocomplete="postal-code" inputmode="numeric" pattern="[0-9]{5}" maxlength="5" required></label>' if valuation else '<label>Preferred area<input name="city" id="preferred-city" autocomplete="address-level2"></label>'
 return f'''<form class="request-form" data-request="{'valuation' if valuation else 'contact'}"><h2>{'Tell Emad about your home.' if valuation else 'Start the conversation.'}</h2><p>Fill this out to prepare an email. You’ll review it before opening your email app and sending it.</p><div class="fields">{purpose}<label>Your name<input name="name" autocomplete="name" required maxlength="120"></label><label>Email<input name="email" type="email" autocomplete="email" spellcheck="false" required maxlength="200"></label><label>Phone (optional)<input name="phone" type="tel" autocomplete="tel" maxlength="40"></label>{address}<label>Timing<select name="timing"><option>Just exploring</option><option>Within 3 months</option><option>3–6 months</option><option>6+ months</option></select></label><label class="full">{'Condition, improvements & anything else Emad should know' if valuation else 'How can we help?'}<textarea name="message" rows="5" maxlength="3000" required></textarea></label></div><p class="form-note">Your details stay in this page until you choose to send through your email app. <a href="/privacy/">Privacy details</a>.</p><button class="button primary" type="submit">Review my request <span aria-hidden="true">↗</span></button><noscript><p>To prepare a request here, enable JavaScript. Or email superiorservicerealtor@gmail.com directly.</p></noscript><div class="request-review" hidden tabindex="-1"><h3>Your email is ready to review.</h3><pre></pre><div class="action-row"><a class="button dark email-request" href="mailto:superiorservicerealtor@gmail.com">Open email app ↗</a><button class="button outline copy-request" type="button">Copy message</button><button class="button outline download-request" type="button">Save request</button></div><p class="request-status" aria-live="polite">Nothing has been sent. Send the message from your email app to complete your request.</p></div></form>'''
page('home-value','What is my home worth?',hero('A personal home valuation','Your home is more<br>than a number.','Tell Emad about the address, condition, and improvements. Start a valuation conversation specific to your property.')+'<section class="section wrap form-layout"><aside><h2>A better<br>starting point.</h2><p>This is a request for Emad’s review—not an instant automated estimate.</p><p>Include recent improvements and your timing. Those details help make the first conversation more useful.</p><h3>Prefer to talk?</h3><a class="big-phone" href="tel:+12099144751">209.914.4751</a></aside>'+form(True)+'</section>')
page('contact','Contact Emad',hero('Let’s talk','A direct line.<br>A real conversation.','Selling, buying, relocating, or just working out what comes next—reach Emad and the team here.')+'<section class="section wrap form-layout"><aside><p class="kicker">Emad A. Basma</p><h2>Your next move<br>starts here.</h2><a class="big-phone" href="tel:+12099144751">209.914.4751</a><p><a href="mailto:superiorservicerealtor@gmail.com">superiorservicerealtor@gmail.com</a></p><address>Agent4Life Realty<br>35 East 10th Street<br>Tracy, CA 95376</address><p>DRE #01441193</p><a class="inline-link" href="/team/">Contact another team member</a></aside>'+form()+'</section>')
page('privacy','Privacy & contact requests',hero('Your information','Your details.<br>Handled clearly.','How this version of the Agent4Life website handles contact requests and browsing.')+split('Contact requests.','<p>The contact and home valuation forms prepare a message in your browser. They do not submit information to Agent4Life automatically. You can review the text, copy it, save it to your device, or open it in your email app.</p><p>If you send the email, the recipient receives the information you included. Contact Agent4Life at <a href="mailto:superiorservicerealtor@gmail.com">superiorservicerealtor@gmail.com</a> with questions about a message you have sent or to request a correction.</p>')+split('Browsing<br>and services.','<p>This build does not include advertising trackers, analytics scripts, a newsletter subscription, or browser storage of your form details. The website host may process technical information when delivering pages.</p><p>Typography is loaded from Google Fonts, which requires a connection from your browser to Google’s servers. Links to social networks, virtual tours, or email applications take you to services with their own privacy practices.</p><p>This notice describes this version of the site. It should be updated if direct form delivery, analytics, or other services are added.</p>'))


# Compact individual team profile, kept in the build so listing updates preserve it.
nizar_body = '<section class="nizar-profile wrap"><a class="inline-link" href="/team/">← Meet the team</a><div class="nizar-grid"><div class="nizar-copy"><p class="kicker">Agent4Life Realty · Tracy, California</p><h1>Nizar<br>Basma<span class="period">.</span></h1><h2>Local roots.<br>A clear head for your next move.</h2><p>Raised in Tracy, Nizar brings a background in tech and a detail-focused approach to real estate. He helps buyers and sellers work through the questions, compare their options, and feel informed at every step.</p><div class="action-row"><a class="button primary" href="mailto:basmarealty@gmail.com?subject=Let%E2%80%99s%20talk%20about%20my%20next%20move">Email Nizar ↗</a><a class="nizar-phone" href="tel:+12099144731">209.914.4731</a></div><div class="nizar-social"><a href="https://www.zillow.com/profile/nizarbasma">Zillow profile ↗</a><a href="https://www.instagram.com/nizarb14/">Instagram ↗</a></div></div><figure class="nizar-photo"><img src="/assets/img/team-nizar.jpg" alt="Nizar Basma" width="350" height="500" fetchpriority="high"><figcaption>Part of Team Basma.<br>Here for your next chapter.</figcaption></figure></div></section><section class="nizar-proof"><div class="wrap"><p class="kicker">A client’s perspective</p><blockquote>“He helped me purchase two homes and consistently went above and beyond throughout the entire process.”</blockquote><p>Sarkis Fesliyan <span>·</span> <a href="https://www.zillow.com/profile/nizarbasma">Zillow review, February 2026 ↗</a></p></div></section>'
nizar_body += '<section class="nizar-approach wrap"><div class="nizar-local-photo"><img src="/assets/img/nizar-skyline.png" alt="Nizar with the San Francisco skyline at night" width="1479" height="1063" loading="lazy"></div><div><p class="kicker">Working with Nizar</p><h2>A local perspective.<br>An eye for the details.</h2><p>Growing up in Tracy gives Nizar a personal connection to the place. His background in tech brings a thoughtful approach to the details that come with a move.</p><p>Bring your questions, your must-haves, and the things you’re still figuring out. Start with a conversation about what matters to you.</p></div></section><section class="nizar-next"><div class="wrap"><div><p class="kicker">Let’s start there.</p><h2>What’s your<br>next chapter?</h2></div><div><p>A first home. A new neighborhood. A sale you’ve been considering. Talk it through with Nizar.</p><div class="action-row"><a class="button white" href="mailto:basmarealty@gmail.com?subject=I%E2%80%99m%20thinking%20about%20buying">I’m looking to buy <span aria-hidden="true">↗</span></a><a class="button nizar-sell" href="mailto:basmarealty@gmail.com?subject=I%E2%80%99m%20thinking%20about%20selling">I’m thinking of selling <span aria-hidden="true">↗</span></a></div></div></div></section>'
page('team/nizar-basma','Nizar Basma',nizar_body,'Meet Nizar Basma, a Tracy-raised real estate agent with Agent4Life Realty. Connect directly about buying or selling your next home.')
team_path=OUT/'team/index.html'
team_html=team_path.read_text(encoding='utf-8')
team_html=team_html.replace('<h2>Nizar Basma</h2>','<h2><a href="/team/nizar-basma/">Nizar Basma ↗</a></h2>')
start=team_html.index('<article id="nizar">');end=team_html.index('</article>',start)
team_html=team_html[:start]+team_html[start:end].replace('2099144751','2099144731').replace('209.914.4751','209.914.4731')+team_html[end:]
team_path.write_text(team_html,encoding='utf-8')


# Individual profiles share the compact Nizar structure, with distinct source-grounded stories.
profiles=[
 dict(slug='rosendo-serna',first='Rosendo',last='Serna',key='rosendo',image='team-rosendo.jpg',phone='2094790358',email='serna2239@comcast.net',headline='A steady hand.<br>A promise kept.',intro='Born and raised in Stockton and a Manteca resident since 1995, Rosendo brings local knowledge and 26 years of correctional and deputy service to his work with buyers and sellers.',caption='Stockton roots.<br>A Manteca perspective.',links=[('https://www.zillow.com/profile/Rosendo0','Zillow profile'),('https://www.linkedin.com/in/rosendoserna/','LinkedIn')],proofTitle='A client’s perspective',proof='Working with Rosendo has been a pleasure. He is one of the most helpful people I have met on Zillow.',by='yasiraf · Zillow review, July 2022',source='https://www.zillow.com/profile/Rosendo0',photo='city-manteca.jpg',alt='A view across Manteca',sub='Experience that<br>stays with you.',text='Before real estate, Rosendo served with the Santa Clara County Sheriff’s Office. His approach is grounded in integrity, discipline, and following through on his word.',text2='His guiding principle is simple: “Make a promise, keep a promise.” Bring your goals and questions, and start a conversation about the move you have in mind.'),
 dict(slug='sonya-jones',first='Sonya',last='Jones',key='sonya',image='team-sonya.jpg',phone='2098793344',email='sellwithsonya@yahoo.com',headline='A place to call home.<br>Someone in your corner.',intro='Sonya brings the care and patience of her healthcare background to real estate. As a mother and a member of Team Basma, she understands how personal the decision to move can be.',caption='Part of Team Basma.<br>Care in every conversation.',links=[],proofTitle='Her approach',proof='A home is personal. The guidance should be, too.',by='',source='',photo='basma-family.png',alt='Sonya with Emad and Nizar Basma',sub='Family is part<br>of the story.',text='Sonya works alongside her father, Emad, and brother, Nizar. That family connection is part of the Agent4Life story—and her own understanding of what makes a place feel like home.',text2='Her experience as a radiology technician carries into the way she works with people: listening, explaining, and helping them feel supported through an important decision.'),
 dict(slug='jamese-johnson',first='Jamese',last='Johnson',key='jamese',image='jamese-portrait.png',phone='2096400423',email='jamesejohnsonrealty@gmail.com',headline='Your next chapter.<br>Someone who gets it.',intro='Buying her own home at 28 inspired Jamese to help others do the same. She brings a background in nonprofit projects and clinical research to guiding clients across the San Joaquin and Tri-Valley areas.',caption='A personal milestone.<br>A reason to help others.',links=[],proofTitle='Where it began',proof='Her own first home made the possibility real.',by='',source='',photo='jamese-hiking.png',alt='Jamese hiking near the Hollywood sign',sub='People first.<br>Details handled.',text='Jamese knows what it feels like to work toward a home that once seemed out of reach. That experience shapes the encouragement she brings to her clients.',text2='Her work in clinical research and nonprofit projects involved coordination, communication, and solving problems. She brings those same skills to helping people navigate a move.')
]
for a in profiles:
 full=a['first']+' '+a['last'];phone=a['phone'];display=phone[:3]+'.'+phone[3:6]+'.'+phone[6:]
 social=''.join('<a href="'+url+'">'+label+' ↗</a>' for url,label in a['links'])
 proof=('<blockquote>“'+a['proof']+'”</blockquote><p><a href="'+a['source']+'">'+a['by']+' ↗</a></p>') if a['source'] else '<h2 class="profile-statement">'+a['proof']+'</h2>'
 body=f"""<section class="nizar-profile agent-profile agent-{a['key']} wrap"><a class="inline-link" href="/team/">← Meet the team</a><div class="nizar-grid"><div class="nizar-copy"><p class="kicker">Agent4Life Realty</p><h1>{a['first']}<br>{a['last']}<span class="period">.</span></h1><h2>{a['headline']}</h2><p>{a['intro']}</p><div class="action-row"><a class="button primary" href="mailto:{a['email']}">Email {a['first']} ↗</a><a class="nizar-phone" href="tel:+1{phone}">{display}</a></div><div class="nizar-social">{social}</div></div><figure class="nizar-photo"><img src="/assets/img/{a['image']}" alt="{full}" width="350" height="500" fetchpriority="high"><figcaption>{a['caption']}</figcaption></figure></div></section><section class="nizar-proof"><div class="wrap"><p class="kicker">{a['proofTitle']}</p>{proof}</div></section><section class="nizar-approach agent-story agent-{a['key']} wrap"><div class="nizar-local-photo"><img src="/assets/img/{a['photo']}" alt="{a['alt']}" width="800" height="850" loading="lazy"></div><div><p class="kicker">Working with {a['first']}</p><h2>{a['sub']}</h2><p>{a['text']}</p><p>{a['text2']}</p></div></section><section class="nizar-next"><div class="wrap"><div><p class="kicker">Let’s start with you.</p><h2>What’s your<br>next chapter?</h2></div><div><p>Buying, selling, or thinking it through? Talk directly with {a['first']} about what comes next.</p><div class="action-row"><a class="button white" href="mailto:{a['email']}?subject=I%E2%80%99m%20thinking%20about%20buying">I’m looking to buy ↗</a><a class="button nizar-sell" href="mailto:{a['email']}?subject=I%E2%80%99m%20thinking%20about%20selling">I’m thinking of selling ↗</a></div></div></div></section>"""
 page('team/'+a['slug'],full,body)
team_html=team_path.read_text(encoding='utf-8')
for a in profiles:
 full=a['first']+' '+a['last']
 team_html=team_html.replace('<h2>'+full+'</h2>','<h2><a href="/team/'+a['slug']+'/">'+full+' ↗</a></h2>')
# Team directory retains Jamese’s original headshot.
team_path.write_text(team_html,encoding='utf-8')

# Listings have real static pages; filters only enhance the complete HTML.
options=''.join(f'<option>{E(c)}</option>' for c in sorted({p['city'] for p in listings}))
filters=f'''<form id="listing-filters" class="listing-filters"><label>Status<select name="status"><option value="all">All properties</option><option value="active">For sale</option><option value="pending">Pending</option><option value="sold">Sold</option></select></label><label>City<select name="city"><option value="">All cities</option>{options}</select></label><label>Maximum price<input name="max" type="number" min="0" step="1" inputmode="numeric" placeholder="Any price"></label><label>Bedrooms<select name="beds"><option value="0">Any</option><option value="3">3+</option><option value="4">4+</option><option value="5">5+</option></select></label><label>Search address<input name="q" type="search" placeholder="Street or address"></label><label>Sort<select name="sort"><option value="high">Price: high to low</option><option value="low">Price: low to high</option><option value="address">Address</option></select></label><button class="button dark" type="submit">Apply filters</button><button class="button outline" type="reset">Reset</button></form>'''
page('listings','Explore properties',hero('Agent4Life properties','A closer look<br>at your next move.','Browse available and sold properties, explore the details, and ask Emad about a home that catches your eye.')+'<section class="section wrap"><p class="data-note">'+E(data['sourceNote'])+'</p>'+filters+'<p id="result-count" aria-live="polite">'+str(len(listings))+' properties</p><div class="catalog">'+''.join(card(p) for p in listings)+'</div><div class="empty-results" hidden><h2>No homes match these filters.</h2><p>Try a wider price range or another city. You can also ask the team to help with your search.</p>'+link('/contact/?intent=Buying','Tell us what you’re looking for')+'</div><p class="availability">Property information and measurements should be independently verified. Listing-office attribution is shown for each home. This is a selected property collection, not a complete market search.</p></section>')
for p in listings:
 media=''.join(picture(img,p['address']+' property photo') for img in p['images']) or '<div class="no-photo">Contact Emad for property photography.</div>'
 priceLabel='Sold price' if p['status']=='sold' else 'Asking price'
 title=E(p['address']);status={'active':'For sale','sold':'Sold','pending':'Pending','showcase':'Property showcase'}[p['status']]
 body=f'<section class="property-top wrap"><a class="inline-link" href="/listings/">← All properties</a><div class="property-heading"><div><p class="kicker">{status} · {E(p["city"])}</p><h1>{title}</h1><p>{E(p["city"])}, CA {E(p["zip"])}</p></div><p class="detail-price"><small>{priceLabel}</small>${p["price"]:,}</p></div></section><div class="wrap property-gallery">{media}</div><section class="section wrap property-body"><div><div class="property-numbers"><p><strong>{p["beds"]}</strong>Bedrooms</p><p><strong>{E(p["baths"])}</strong>Bathrooms</p><p><strong>{p["sqft"]:,}</strong>Square feet</p></div><h2>The details.</h2><p>{E(p.get("description") or "Explore this "+p["city"]+" property with Emad. Contact the team for a personal walkthrough of the home’s features and current details.")}</p><dl><dt>Listing number</dt><dd>{E(p["id"])}</dd><dt>Listing office</dt><dd>{E(p["listingOffice"])}</dd><dt>Information date</dt><dd>{E(p["sourceDate"])}</dd></dl><p class="availability">{E(data["sourceNote"])} Measurements and property information should be independently verified.</p></div><aside class="property-inquiry"><p class="kicker">Talk with Emad</p><h2>{"Ask about similar homes." if p["status"]=="sold" else "Take the next look."}</h2><p>Get answers about this property and discuss your next step.</p>{link("/contact/?intent=Buying&property="+quote(p["address"]),"Ask about this home")}<a class="big-phone" href="tel:+12099144751">209.914.4751</a>'+(link(p['tourUrl'],'View the property tour','outline') if p.get('tourUrl') else '')+'</aside></section>'
 page('listings/'+p['slug'],p['address'],body)

# Preserve the approved homepage composition, replace navigation and connect sections.
home=(ROOT/'backups/approved-homepage/index.html').read_text(encoding='utf-8')
home=re.sub(r'<header class="header">.*?</header>',header,home,flags=re.S)
home=re.sub(r'<footer>.*?</footer>',footer,home,flags=re.S)
home=home.replace('href="#contact"','href="/contact/"').replace('href="#approach">See the difference','href="/sellers/">See the difference')
for section,route,label in [('approach','sellers','Explore the selling plan'),('emad','about','More about Emad'),('team','team','Meet the team & connect'),('communities','communities','Explore all six communities')]:
 pattern=r'(<section id="'+section+r'".*?)(</section>)'
 home=re.sub(pattern,lambda m:m[1]+f'<div class="wrap section-more">{link("/"+route+"/",label,"dark")}</div>'+m[2],home,count=1,flags=re.S)
home=home.replace('<p class="quote-author">','<p><a class="inline-link" href="/testimonials/">More client stories ↗</a></p><p class="quote-author">')
featured=[p for p in listings if p.get('featured') and p['status']!='sold'][:3]
if len(featured)<3:featured+=( [p for p in listings if p not in featured][:3-len(featured)] )
featureHtml=''
for i,p in enumerate(featured):
 img=picture(p['images'][0],p['address']) if p['images'] else '<div class="no-photo">Ask Emad for photos</div>'
 featureHtml+=f'<a class="property {"property-feature" if i==0 else ""}" href="/listings/{p["slug"]}/">{img}<span class="property-caption"><span><small>{E(p["city"])}</small><strong>{E(p["address"])}</strong><span>{p["beds"]} bedrooms · {p["sqft"]:,} sq. ft.</span></span><span class="circle" aria-hidden="true">↗</span></span></a>'
home=re.sub(r'<div class="wrap property-grid">.*?</div><p class="wrap availability">.*?</p>', '<div class="wrap property-grid">'+featureHtml+'</div><div class="wrap section-more">'+link('/listings/','Browse all properties','dark')+'<p class="availability">'+E(data['sourceNote'])+'</p></div>',home,flags=re.S)
home=re.sub(r'<dialog id="property-dialog".*?</dialog>','',home,flags=re.S)
home=home.replace('<h3>Nizar Basma</h3>','<h3><a href="/team/nizar-basma/">Nizar Basma ↗</a></h3>')
for a in profiles:
 full=a['first']+' '+a['last']
 home=home.replace('<h3>'+full+'</h3>','<h3><a href="/team/'+a['slug']+'/">'+full+' ↗</a></h3>')
# Homepage retains Jamese’s original approved headshot.
(OUT/'index.html').write_text(home,encoding='utf-8')
# Cover every captured old route plus property-detail URLs. Static fallback works on basic hosts;
# _redirects expresses permanent redirects for hosts that support it.
routes=json.loads((ROOT/'research/page-inventory.json').read_text(encoding='utf-8'));mapping={}
canonical=['','team/rosendo-serna','team/sonya-jones','team/jamese-johnson','team/nizar-basma','sellers','buyers','home-value','communities','about','team','testimonials','contact','privacy','listings']
for item in routes:
 old=item['url'];target=None
 if old=='/' or old.strip('/') in canonical:continue
 if old.startswith('/seller/'):target='/sellers/'
 elif old.startswith(('/buyer/','/finance/')) or old=='/financing/':target='/buyers/'
 elif old.startswith('/community/'):target='/communities/#'+old.strip('/').split('/')[-1]
 elif old=='/agents/nizar-basma/':target='/team/nizar-basma/'
 elif old in ['/agents/rosendo-serna/','/agents/sonya-jones/','/agents/jamese-johnson/']:target='/team/'+old.strip('/').split('/')[-1]+'/'
 elif old.startswith('/agents/'):
  slug=old.strip('/').split('/')[-1];target='/about/' if slug=='emad-basma' else '/team/#'+slug.split('-')[0]
 elif old in ['/what-is-my-home-worth/','/get-a-free-home-valuation/']:target='/home-value/'
 elif old=='/sold/':target='/listings/?status=sold'
 elif old in ['/properties/','/search/']:target='/listings/'
 elif old in ['/find-my-dream-home/','/help-me-relocate/']:target='/contact/?intent='+('Buying' if old=='/find-my-dream-home/' else 'Relocating')
 elif old=='/privacy-policy/':target='/privacy/'
 elif old=='/social-media/':target='/contact/'
 elif old.startswith('/blog/') or old=='/latest-news/':target='/buyers/' if 'buyer' in old else '/sellers/'
 elif old=='/sitemap/':target='/'
 elif old.startswith('/listings/'):target='/listings/'
 if target:mapping[old]=target
history_file=ROOT/'plans/listing-history.json'
history=json.loads(history_file.read_text(encoding='utf-8')) if history_file.exists() else {}
current={p['id']:p for p in listings}
for mid,old in history.items():
 target='/listings/'+current[mid]['slug']+'/' if mid in current else '/listings/'
 if mid not in current or old['slug']!=current[mid]['slug']:mapping['/listings/'+old['slug']+'/']=target
 if old.get('legacyPath'):mapping[old['legacyPath']]=target
for p in listings:
 if p.get('legacyPath'):mapping[p['legacyPath']]='/listings/'+p['slug']+'/'
 history[p['id']]={'slug':p['slug'],'legacyPath':p.get('legacyPath','')}
history_file.write_text(json.dumps(history,indent=2),encoding='utf-8')
for old,target in mapping.items():
 path=OUT/old.strip('/')/'index.html';path.parent.mkdir(parents=True,exist_ok=True)
 path.write_text(f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url={E(target)}"><title>Page moved | Agent4Life</title><p>This page has moved. <a href="{E(target)}">Continue to Agent4Life</a>.</p></html>',encoding='utf-8')
(OUT/'_redirects').write_text('\n'.join(f'{old} {new} 301' for old,new in mapping.items())+'\n',encoding='utf-8')
(ROOT/'plans/migration-map.json').write_text(json.dumps(mapping,indent=2),encoding='utf-8')
urls=['https://agent4liferealty.com/'+(r+'/' if r else '') for r in canonical]+['https://agent4liferealty.com/listings/'+p['slug']+'/' for p in listings]
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in urls)+'</urlset>',encoding='utf-8')
(OUT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://agent4liferealty.com/sitemap.xml\n',encoding='utf-8')
(OUT/'404.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/site.css"><title>Page not found | Agent4Life</title><main class="section wrap"><p class="kicker">Agent4Life Realty</p><h1>This page has moved on.</h1><p>Let’s get you to the right place.</p>'+link('/','Return home')+' '+link('/listings/','Explore properties','dark')+'</main></html>',encoding='utf-8')
print(f'Built 11 main pages, {len(listings)} property pages, {len(mapping)} legacy redirects.')

