const {chromium}=require('C:/Users/mabac/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs');const assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const routes=[];const data=JSON.parse(fs.readFileSync('implementation/data/listings.json','utf8'));const report=[];fs.mkdirSync('qa/full-site',{recursive:true});
for(const width of [1280,390,320]){await page.setViewportSize({width,height:900});for(const route of routes){const response=await page.goto('http://127.0.0.1:8778/'+(route?route+'/':''));assert.equal(response.status(),200);await page.locator('h1').waitFor();await page.evaluate(()=>document.fonts.ready);await page.locator('img[loading]').evaluateAll(is=>is.forEach(i=>i.loading='eager'));await page.locator('img').evaluateAll(is=>Promise.all(is.map(i=>i.decode().catch(()=>{}))));const check=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,images:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src)}));report.push({width,route:route||'home',...check});await page.screenshot({path:`qa/full-site/${route||'home'}-${width}.png`,fullPage:true});assert(!check.overflow,route+' overflow at '+width);assert.equal(check.images.length,0,route+' images');}console.log('Main routes pass at',width)}
await page.setViewportSize({width:1280,height:900});for(const p of []){await page.goto('http://127.0.0.1:8778/listings/'+p.slug+'/');assert.equal(await page.locator('h1').textContent(),p.address);for(const width of [1280,390,320]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),p.address+' overflow')}}console.log('14 property pages pass at all widths');
await page.goto('http://127.0.0.1:8778/listings/?status=sold');assert.equal(await page.locator('.listing-card:visible').count(),5);await page.selectOption('[name=status]','active');await page.selectOption('[name=city]','Lathrop');await page.locator('#listing-filters button[type=submit]').click();assert.equal(await page.locator('.listing-card:visible').count(),2);await page.fill('[name=max]','1');await page.locator('#listing-filters button[type=submit]').click();assert(await page.locator('.empty-results').isVisible());await page.locator('#listing-filters button[type=reset]').click();await page.waitForFunction(()=>document.querySelectorAll('.listing-card:not([hidden])').length===14);console.log('Filters, empty state, reset pass');
for(const route of ['contact','home-value']){await page.goto('http://127.0.0.1:8778/'+route+'/');await page.fill('[name=name]','Website QA');await page.fill('[name=email]','qa@example.com');await page.fill('[name=message]','Local test only. Nothing sent.');if(route==='home-value'){await page.fill('[name=address]','123 Test Street');await page.fill('[name=city]','Tracy');await page.fill('[name=zip]','95376')}await page.locator('.request-form button[type=submit]').click();assert(await page.locator('.request-review').isVisible());const href=await page.locator('.email-request').getAttribute('href');assert(href.includes('mailto:superiorservicerealtor@gmail.com'));assert(decodeURIComponent(href).includes('qa@example.com'));await page.fill('[name=name]','Changed QA');assert(!(await page.locator('.request-review').isVisible()));}console.log('Both request forms review correctly; no email sent');
await page.goto('http://127.0.0.1:8778/contact/?intent=Buying&property=Test%20Property');assert.equal(await page.inputValue('[name=intent]'),'Buying');assert((await page.inputValue('[name=message]')).includes('Test Property'));await page.setViewportSize({width:390,height:900});await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');
for(const [old,target] of Object.entries(JSON.parse(fs.readFileSync('plans/migration-map.json','utf8')))){await page.goto('http://127.0.0.1:8778'+old);await page.waitForURL('http://127.0.0.1:8778'+target);}
console.log('59 legacy routes reach their replacements');assert.deepEqual(errors,[]);fs.writeFileSync('qa/full-site/results.json',JSON.stringify({pages:report,errors,properties:14,redirects:59,forms:'review only; no external send'},null,2));await browser.close()})();

